exclude: (alembic)
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --config=pyproject.toml ]
        stages: [ pre-commit ]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]
        stages: [ pre-commit ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml, --explicit-package-bases]
        stages: [ pre-commit ]
        additional_dependencies: [ pydantic, types-orjson, types-pytz, types-cachetools, types-protobuf==4.24.0.4 ]
        exclude: ^(tests/|conftest.py|alembic/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: docs/db/schema.md
      - id: end-of-file-fixer
        exclude: docs/db/schema.md
